//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 25-Dec-17 0:11:12
namespace MonopolyGameModel
{
    
    /// <summary>
    /// There are no comments for MonopolyGameEntities in the schema.
    /// </summary>
    public partial class MonopolyGameEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MonopolyGameEntities object using the connection string found in the 'MonopolyGameEntities' section of the application configuration file.
        /// </summary>
        public MonopolyGameEntities() : 
                base("name=MonopolyGameEntities", "MonopolyGameEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MonopolyGameEntities object.
        /// </summary>
        public MonopolyGameEntities(string connectionString) : 
                base(connectionString, "MonopolyGameEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MonopolyGameEntities object.
        /// </summary>
        public MonopolyGameEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MonopolyGameEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
